ENH: split_data and classify_samples to output target metadata
qiime2/q2-sample-classifier pull request #204
Opened 2021-04-07 16:41 UTC by adamovanja

closes #104

Introduced `SamplesData[TrueTargets]` semantic type allows `split_data`and `classify_samples` to output target metadata (`y_train`and `y_test`). `TrueTargets` used instead of previously proposed `Metadata` since latter is already a reserved type name.

2021-05-28 14:20 UTC, nbokulich requested changes
Thanks @adamovanja ! Just a few minor comments in-line.

One other small comment: want to add a transformer to this PR to convert from `TrueTargets` to `Metadata` and vice versa? this will allow a user to view `TrueTargets` as metadata (which would be convenient for viewing this output), and also the reverse transformation probably would/should not be used usually, but I could imagine some use cases for which a workaround would be nice.

2021-05-28 14:20 UTC, nbokulich commented on q2_sample_classifier/plugin_setup.py
> +        'training_targets': 'Table containing true target values of'
I would not refer to this as a table (to avoid confusion with "feature table")... instead perhaps a list of true target values?

2021-05-28 14:20 UTC, nbokulich commented on q2_sample_classifier/plugin_setup.py
> +        'test_targets': 'Table containing true target values of test samples'},
same as above, not a table

2021-05-28 14:20 UTC, nbokulich commented on q2_sample_classifier/plugin_setup.py
> +        'training_targets': 'Table containing true target values of'
same as above, not a table

2021-05-28 14:20 UTC, nbokulich commented on q2_sample_classifier/plugin_setup.py
> +        'test_targets': 'Table containing true target values of test samples'},
...not a table

2021-05-28 14:55 UTC, nbokulich commented on q2_sample_classifier/plugin_setup.py
> +        'training_targets': 'Table containing true target values of'
sounds good!

2021-06-03 16:18 UTC, nbokulich requested changes
Thanks @adamovanja ! Minor tweaks inline (missing spaces in description text)

I did a test run with the new types locally and all looks okay.

Should unit tests be added for the new types? I see that the new types use the PredictionsFormat so additional validation is not required but maybe at least add a couple tests for the transformers? Basically just replicate the same tests used for any SampleData[Predictions] transformers, but to/from SampleData[TrueTargets]

As a follow-up to this PR, changes will be needed in the QIIME 2 docs here: https://github.com/qiime2/docs/blob/master/source/tutorials/sample-classifier.rst

2021-07-21 12:34 UTC, adamovanja commented
Hi @nbokulich, 

Thank you for the feedback.

Upon several tryouts, I have the impression that no additional transformers are needed for the new Semantic Type `SampelData[TrueTargets]` as it is registered as a `PredictionsFormat` that already has all transformers needed (`PredictionsFormat` <-> `pd.Series` & `qiime2.Metadata`). I have, however, added two tests that verify the new DirFmt `TrueTargetsDirectoryFormat`. Do let me know if I am missing a transformation that is not covered with the current setup. 

As for the changes in the QIIME2 docs, I believe the new code changes don't break anything in the previous tutorial flow. One could however add a description of the new outputs of `classify_samples`: `training_targets.qza` and `test_targets.qza`. Do you agree?

2021-07-21 13:18 UTC, nbokulich approved these changes
LGTM Thanks @adamovanja !

Yes, I think the new tests you added to verify the registration were the only missing tests. All looks good now :)

As for the docs update, yes, I think adding a very short description of the new outputs would be desired, so that users following the tutorial know what these are.

2021-07-22 18:53 UTC, merged